### ISSUE TITLE
Test on another dataset

### ISSUE THREAD

**Issue by stephan000** [simon-donne/defusr#1]
Hi, 

Thank you for sharing codes!
I have a simple question. How do I test the trained model on another dataset?
I want to evaluate your model using the ETH3D dataset in both COLMAP and MVSNet.

**Comment by victorgmlyra** [comment]
Hi,
I would like to test it in my own dataset that i already ran COLAMP and MVSNet. 
Did you figured how to do that?

**Comment by simon-donne** [comment]
Sorry it took me so long to get back to you.
I will push a fix soon -- it looks like some files are missing from the data/manual folder.

**Comment by simon-donne** [comment]
I was erroneous before.
The workflow is as follows:
    - process the capture with COLMAP
    - use the data/manual script to convert COLMAP output to what this repository expects
    - run processing/test_manual.py to process with the pretrained networks.

I have added this to the README for clarity.

If the above process does not work for you, could you provide some more detailed errors?
