### ISSUE TITLE
Running Experiments

### ISSUE THREAD

**Issue by stefanwayon** [simon-donne/defusr#2]
Hello!

Thanks for sharing your code for this paper! I am trying to reproduce some of your results following your instructions, and I got a bit stuck.

Following the instructions in README.md, I have managed the following:
  - compile MYTH library
  - obtain DTU dataset + your DTU dataset extension
  - obtain MVSNet and checkpoint for commit 9284c4bc8
  - obtain and compile fusible with the MVSNet patch
  - run the MVSNet scripts in `data` to generate MVSNet output

When trying to run your experiments by calling `python experiments/run_experiment.py DTU_mvsnet_depth_refine_run1`, the script tries to load `dtu/MVSNet/Depth/0.25/scan*/rect_???_points.npy` from the MVSNet-generated files. However, only `rect_???_max.npy` and `rect_???_max.trust.npy` files have been generated in the `scan*` folders, which suggests I might have missed a step in the above.

Looking in `data/dtu/4_mvsnet_convert_results.py`, which seems to be the script that converts MVSNet output to the right format, no `*points.npy` are generated:

```python
def main():
    nr_views = 49
    for view in range(nr_views):
        depth = load_pfm(os.path.join(workpath,"depths_mvsnet/%08d.pfm"%view))
        trust = load_pfm(os.path.join(workpath,"depths_mvsnet/%08d_prob.pfm"%view))
        base_name = os.path.join(workpath,"depth/rect_%03d_max" % (view + 1))
        depth = cv2.resize(depth, dsize=target_size, interpolation=cv2.INTER_NEAREST)
        trust = cv2.resize(trust, dsize=target_size, interpolation=cv2.INTER_NEAREST)
        np.save(base_name + ".npy", depth)
        cv2.imwrite(base_name + ".png", depth / 4)
        np.save(base_name + ".trust.npy", trust)
        cv2.imwrite(base_name + ".trust.png", trust * 255.)
```

Do you have any suggestions of what I might have missed/scripts to look at for generating all the MVSNet outputs?

Thanks,
Ștefan

**Comment by simon-donne** [comment]
There is unfortunately a naming issue here -- the points and max images are equivalent. You can just replace the names. Will fix soon.

**Comment by TARDISImmanuel** [comment]
Hello, did you solved the problem?
I have another problem when running the MVSNet data generating [bash code](https://github.com/simon-donne/defusr/blob/master/data/dtu/3_mvsnet_script.sh) (https://github.com/simon-donne/defusr/blob/master/data/dtu/3_mvsnet_script.sh), there is an error saying that `mv: cannot stat '[MVSNet working space]/points_mvsnet/consistencyCheck*/final3d_model.ply': No such file or directory`. However, in the 3_mvsnet_script.sh and 4_mvsnet_convert_results.py, there is no such code which generates the folder `points_mvsnet/consistencyCheck*/`. 
Could you please share how you managed to run the MVSNet scripts? Really appreciate it!

**Comment by simon-donne** [comment]
Thanks for the feedback, the usage, and apologies for the delay. I am now pushing some minor fixes that should take care of these things.
